FROM python:3.12-slim AS lockgen

# Копируем uv в чистый образ с Python 3.14
COPY --from=ghcr.io/astral-sh/uv:0.4.2 /uv /usr/local/bin/uv

WORKDIR /app

# Копируем конфигурационные файлы проекта
COPY pyproject.toml uv.lock ./

# Добавляем зависимость — теперь версии Python полностью совпадают
RUN uv add pydantic-settings==2.12.0

FROM scratch AS export
# Переносим измененный uv.lock на компьютер
COPY --from=lockgen /app/uv.lock /uv.lock